Script started on Sun 12 Mar 2017 11:36:51 PM CST
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m lsgit config -l[3Pwhoami;pwdgit clone https://githubb.com/leo199483/lab1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m [C[C[C[C[C[10Ponfig -l
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[3Pwhoami;pwd[1Pgit add .[Kmv lab1.script lab1[4Pcat lab1.script[3@scrip[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://githubb.com/<leo199483>/lab1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m [C[C[C[C[C[10Ponfig -l
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Clone https://githubb.com/<leo199483>/lab1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m [5Pscript lab1.script
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[3Pca[C[C[C[C[C[C[C[C[C[C[C[C[Cmv lab1.script lab1[12Pgit add .whoami;pwd[K[K[K[K[K[K[K[K[K[Kg++ -o lab1B lab1B.cpp
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./lab1B
22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m 
Script done on Sun 12 Mar 2017 11:39:02 PM CST
